d = {}

name = input("Enter friend's name: ")
lang = input("Enter friend's favorite programming language: ")
d.update({name: lang})
name = input("Enter friend's name: ")
lang = input("Enter friend's favorite programming language: ")
d.update({name: lang})
name = input("Enter friend's name: ")
lang = input("Enter friend's favorite programming language: ")
d.update({name: lang})
name = input("Enter friend's name: ")
lang = input("Enter friend's favorite programming language: ")
d.update({name: lang})
print (d)